version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql_db
    ports: 
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "library"
    networks:
      - library-network

  library-front:
    build: ./library-front
    container_name: library-front
    ports:
      - "3000:3000"
    volumes:
      - ./library-front:/usr/app
    networks:
      - library-network
    depends_on:
      - mysql

  library-api:
    build: ./library-api
    container_name: library-api
    ports:
      - "8000:8000"
    volumes:
      - ./library-api:/usr/app
    networks:
      - library-network
    depends_on:
      - mysql

networks:
  library-network:

volumes:
  db: